## Γραμμική άλγεβρα

Η διανυσματοποίηση κώδικα είναι το κλειδί για τη σύνταξη αποτελεσματικών αριθμητικών υπολογισμών με Python/Numpy. 

In [1]:
from numpy import *

### Πολλαπλασιασμός πίνακα με αριθμό

Μπορούμε να χρησιμοποιήσουμε τους συνηθισμένους αριθμητικούς τελεστές για να πολλαπλασιάσουμε, να προσθέσουμε, να αφαιρέσουμε και να διαιρέσουμε arrays με αριθμούς.

In [2]:
v1 = arange(0, 5)

In [3]:
v1

array([0, 1, 2, 3, 4])

In [4]:
v1 * 2

array([0, 2, 4, 6, 8])

In [5]:
v1 + 2

array([2, 3, 4, 5, 6])

In [6]:
A = array([[n+m*10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [7]:
A * 2, A + 2

(array([[ 0,  2,  4,  6,  8],
        [20, 22, 24, 26, 28],
        [40, 42, 44, 46, 48],
        [60, 62, 64, 66, 68],
        [80, 82, 84, 86, 88]]),
 array([[ 2,  3,  4,  5,  6],
        [12, 13, 14, 15, 16],
        [22, 23, 24, 25, 26],
        [32, 33, 34, 35, 36],
        [42, 43, 44, 45, 46]]))

### Πολλαπλασιασμός ανά στοιχείο

Όταν προσθέτουμε, αφαιρούμε, πολλαπλασιάζουμε και διαιρούμε arrays μεταξύ τους, η προεπιλεγμένη συμπεριφορά είναι πράξεις ενα προς ένα μεταξύ των στοιχείων:

In [8]:
A * A # πολλαπλασιασμός ανά στοιχείο

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [9]:
v1 * v1

array([ 0,  1,  4,  9, 16])

Αν πολλαπλασιάσουμε arrays με συμβατά μεγέθη, παίρνουμε έναν πολλαπλασιασμό ανα στοιχείο κάθε σειράς:

In [11]:
A.shape, v1.shape

((5, 5), (5,))

In [10]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [11]:
v1

array([0, 1, 2, 3, 4])

In [12]:
A * v1

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

### Άλγεβρα πινάκων

Τι γίνεται με τον πολλαπλασιασμό πινάκων; Υπάρχουν δύο τρόποι. Μπορούμε είτε να χρησιμοποιήσουμε τη συνάρτηση «dot», η οποία εφαρμόζει έναν πολλαπλασιασμό πίνακα-πίνακα, πίνακα-διάνυσματος ή εσωτερικό γινόμενο:

In [13]:
dot(A, A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [14]:
dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [15]:
dot(v1, v1)

30

Μπορούμε αντί για dot(A,A) να έχουμε απευθείας Α @ Α για πολλαπλασιασμό πινάκων

In [16]:
v1 @ v1

30

In [17]:
A @ A

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

## Άσκηση

Κατασκευάστε τους πίνακες Pauli: 

$
\sigma_1 =
\begin{bmatrix}
0 & 1 \\
1 & 0
\end{bmatrix}
$
$
\sigma_2 =
\begin{bmatrix}
0 & -i \\
i & 0
\end{bmatrix}
$
$
\sigma_3 =
\begin{bmatrix}
1 & 0 \\
0 & -1
\end{bmatrix}
$

και αποδείξτε ότι $\sigma_i^2 = I, i=1,2,3$

In [21]:
sigma_x = array([[0, 1], [1, 0]])
sigma_y = array([[0, -1j], [1j, 0]])
sigma_z = array([[1, 0], [0, -1]])

dot(sigma_x,sigma_x), dot(sigma_y,sigma_y), dot(sigma_z,sigma_z)

(array([[1, 0],
        [0, 1]]),
 array([[1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j]]),
 array([[1, 0],
        [0, 1]]))

Εναλλακτικά, μπορούμε να ορίσουμε τα αντικείμενα του πίνακα στον τύπο «matrix». Αυτό αλλάζει τη συμπεριφορά των τυπικών αριθμητικών τελεστών `+, -, *` για χρήση της άλγεβρας πινάκων.

In [18]:
M = matrix(A)
v = matrix(v1).T # φτιάχνει τον ανάστροφο

In [20]:
v

matrix([[0],
        [1],
        [2],
        [3],
        [4]])

In [21]:
M * M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [21]:
M * v

matrix([[ 30],
        [130],
        [230],
        [330],
        [430]])

In [22]:
# εσωτερικό γινόμενο
v.T * v

matrix([[30]])

In [27]:
# με αντικείμενα matrix, ισχύει η τυπική άλγεβρα των πινάκων
v + M*v

matrix([[ 30],
        [131],
        [232],
        [333],
        [434]])

Αν προσπαθήσουμε να προσθέσουμε, να αφαιρέσουμε ή να πολλαπλασιάσουμε αντικείμενα με ασύμβατα σχήματα, λαμβάνουμε ένα σφάλμα:

In [23]:
v = matrix([1,2,3,4,5,6]).T

In [24]:
shape(M), shape(v)

((5, 5), (6, 1))

In [25]:
M * v

ValueError: shapes (5,5) and (6,1) not aligned: 5 (dim 1) != 6 (dim 0)

Δείτε επίσης τις σχετικές συναρτήσεις: `inner`, `outer`, `cross`, `kron`, `tensordot`. Δοκιμάστε για παράδειγμα «help(kron)».

### Μετασχηματισμοί πινάκων

Παραπάνω χρησιμοποιήσαμε το «.T» για να βρούμε τον ανάστροφο «v». Θα μπορούσαμε επίσης να είχαμε χρησιμοποιήσει τη συνάρτηση «transpose» για να πετύχουμε το ίδιο πράγμα.

Άλλες μαθηματικές συναρτήσεις που μετασχηματίζουν αντικείμενα matrix είναι:

In [26]:
C = matrix([[1j, 2j], [3j, 4j]])
C

matrix([[0.+1.j, 0.+2.j],
        [0.+3.j, 0.+4.j]])

In [27]:
conjugate(C)

matrix([[0.-1.j, 0.-2.j],
        [0.-3.j, 0.-4.j]])

Ερμιτιανό συζυγές: ανάστροφος + συζυγής

In [28]:
C.H

matrix([[0.-1.j, 0.-3.j],
        [0.-2.j, 0.-4.j]])

Μπορούμε να εξαγάγουμε τα πραγματικά και τα φανταστικά μέρη πινάκων μιγαδικών τιμών χρησιμοποιώντας «πραγματικό» και «εικόνα»:

In [29]:
real(C) # ίδιο με: C.real

matrix([[0., 0.],
        [0., 0.]])

In [30]:
imag(C) # ίδιο με: C.imag

matrix([[1., 2.],
        [3., 4.]])

η απόλυτη τιμή

In [31]:
abs(C)

matrix([[1., 2.],
        [3., 4.]])

### Υπολογισμοί πινάκων

#### Αντίστροφος

In [32]:
linalg.inv(C) # ισοδύναμο με C.I

matrix([[0.+2.j , 0.-1.j ],
        [0.-1.5j, 0.+0.5j]])

In [33]:
C.I * C

matrix([[ 1.00000000e+00+0.j,  8.88178420e-16+0.j],
        [-5.55111512e-17+0.j,  1.00000000e+00+0.j]])

#### Ορίζουσα

In [35]:
linalg.det(C)

(2.0000000000000004+0j)

In [123]:
linalg.det(C.I)

(0.5+0j)

#### Ίχνος

In [36]:
trace(C)

5j

## Άσκηση

Δείξτε ότι:

$$\text{Tr}(\sigma_i \sigma_j) = 2\delta_{ij}$$


In [29]:
sigma_x = array([[0, 1], [1, 0]])
sigma_y = array([[0, -1j], [1j, 0]])
sigma_z = array([[1, 0], [0, -1]])

trace(matrix(sigma_x)*matrix(sigma_y)),trace(matrix(sigma_y)*matrix(sigma_y))

(0j, (2+0j))

Όταν συναρτήσεις όπως «min», «max» κ.λπ. εφαρμόζονται σε πολυδιάστατους πίνακες, μερικές φορές είναι χρήσιμο να εφαρμόζεται ο υπολογισμός σε ολόκληρο τον πίνακα και μερικές φορές μόνο σε βάση γραμμής ή στήλης. Χρησιμοποιώντας το όρισμα «axis» μπορούμε να καθορίσουμε πώς πρέπει να συμπεριφέρονται αυτές οι συναρτήσεις:

In [40]:
m = random.rand(3,3)
m

array([[0.56739957, 0.59859648, 0.93067331],
       [0.06007451, 0.83823257, 0.44052023],
       [0.22114473, 0.40915871, 0.45603858]])

In [41]:
# ολικό μέγιστο
m.max()

0.9306733097215382

In [42]:
# μέγ. σε κάθε στήλη
m.max(axis=0)

array([0.56739957, 0.83823257, 0.93067331])

In [43]:
# μέγ. σε κάθε γραμμή
m.max(axis=1)

array([0.93067331, 0.83823257, 0.45603858])

Οτι ισχύει για matrix ισχύει και για array με εξαίρεση τον Hermitian Conjugate που πρεπει να γίνει με συνδυασμό .conj().T 
στην array

## Ιδιοτιμές και ιδιοδιανύσματα πινάκων

Για να υπολογίσουμε τις ιδιοτιμές και τα ιδιοδιανύσματα ενός πίνακα χρησιμοποιούμε τις συνάρτησεις linarg.eig, linarg.eigh

Προσοχή!!! Δεν μπορεί να χρησιμοποιηθεί η μεταβλητή matrix εδώ, μόνο η array 

In [44]:
# Παράδειγμα εισαγωγής πίνακα 2x2
matrix = array([[3, 1], [1, 3]])

# Υπολογισμός ιδιοτιμών και ιδιοδιανυσμάτων
eigenvalues, eigenvectors = linalg.eig(matrix)

# Εκτύπωση των αποτελεσμάτων
print("Ιδιοτιμές:", eigenvalues)
print("Ιδιοδιανύσματα:\n", eigenvectors)

Ιδιοτιμές: [4. 2.]
Ιδιοδιανύσματα:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


## Άσκηση 

Φτιάξτε μια συνάρτηση που να υπολογίζει τις ιδιοτιμές και τα ιδιοδιανύσματα των Pauli matrices

In [45]:
sigma_x = array([[0, 1], [1, 0]])

# Υπολογισμός ιδιοτιμών και ιδιοδιανυσμάτων
eigenvalues, eigenvectors = linalg.eig(sigma_x)

# Εκτύπωση των αποτελεσμάτων
print("Ιδιοτιμές:", eigenvalues)
print("Ιδιοδιανύσματα:\n", eigenvectors)


Ιδιοτιμές: [ 1. -1.]
Ιδιοδιανύσματα:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


## Αντιγραφή και "βαθιά αντιγραφή"

Για να επιτευχθεί υψηλή απόδοση, οι αναθέσεις στην Python συνήθως δεν αντιγράφουν τα υποκείμενα αντικείμενα. Αυτό είναι σημαντικό για παράδειγμα όταν τα αντικείμενα μεταβιβάζονται μεταξύ συναρτήσεων, για να αποφευχθεί η υπερβολική αντιγραφή στη μνήμη όταν δεν είναι απαραίτητο (τεχνικός όρος: pass by reference).

In [46]:
A = array([[1, 2], [3, 4]])

A

array([[1, 2],
       [3, 4]])

In [47]:
# τώρα ο Β αναφέρεται στα ίδια δεδομένα πίνακα με τον Α
B = A 

In [48]:
B

array([[1, 2],
       [3, 4]])

In [49]:
# Η αλλαγή του Β επηρεάζει τον Α
B[0,0] = 10

B

array([[10,  2],
       [ 3,  4]])

In [50]:
A

array([[10,  2],
       [ 3,  4]])

Αν θέλουμε να αποφύγουμε αυτή τη συμπεριφορά, έτσι ώστε να λαμβάνουμε ένα νέο εντελώς ανεξάρτητο αντικείμενο «Β» που αντιγράφεται από το «Α», τότε πρέπει να κάνουμε ένα λεγόμενο «βαθύ αντίγραφο» (deep copy) χρησιμοποιώντας τη συνάρτηση «copy»:

In [51]:
B = copy(A)

In [52]:
# τώρα, αν τροποποιήσουμε το Β, το Α δεν επηρεάζεται
B[0,0] = -5

B

array([[-5,  2],
       [ 3,  4]])

In [53]:
A

array([[10,  2],
       [ 3,  4]])

## Περαιτέρω ανάγνωση

* http://numpy.scipy.org
* http://scipy.org/Tentative_NumPy_Tutorial
* http://scipy.org/NumPy_for_Matlab_Users - Ένας οδηγός Numpy για χρήστες του MATLAB.

## Zettili άσκηση 3.23 (Σελ.246)

In [54]:
import numpy as np

# Ορισμός της Χαμιλτονιανής με E = 1
E = 1
H = E * np.array([[0, -1j], [1j, 0]])

# (α) Υπολογισμός ιδιοτιμών και ιδιοδιανυσμάτων
eigenvalues, eigenvectors = np.linalg.eig(H)

# (β) Υπολογισμός των πιθανοτήτων μέτρησης ενέργειας
psi_0 = np.array([1, 0])  # Αρχική κατάσταση

# Προβολή της αρχικής κατάστασης στις ιδιοκαταστάσεις
coefficients = np.abs(np.dot(eigenvectors.conj().T, psi_0))**2

# (γ) Υπολογισμός της μέσης τιμής και αβεβαιότητας της ενέργειας
H_squared = np.dot(H, H)

# Βάζω real για να μηδενίσω τυχόν αριθμητικά αριθμητικά σφάλματα
mean_energy = np.real(np.dot(psi_0.conj().T, np.dot(H, psi_0)))
# Εναλλακτικά: mean_energy = np.real(psi_0.conj().T @  (H @ psi_0))
mean_energy_squared = np.real(np.dot(psi_0.conj().T, np.dot(H_squared, psi_0)))
# Εναλλακτικά mean_energy_squared = np.real(psi_0.conj().T @ (H_squared @ psi_0))
energy_uncertainty = np.sqrt(mean_energy_squared - mean_energy**2)

# Με scipy:

from scipy.linalg import expm

# Υπολογισμός της χρονικά εξελισσόμενης κατάστασης |ψ(t)> με expm
# Θεωρώ hbar=1
def psi_t(t):
    U_t = expm(-1j * H * t)  # Ακριβής χρονική εξέλιξη
    return np.dot(U_t, psi_0)

# Εκτύπωση αποτελεσμάτων
t = 1  # Χρόνος t = 1
psi_t_1 = psi_t(t)

print("Ιδιοτιμές:", eigenvalues)
print("Ιδιοσυναρτήσεις", eigenvectors)
print("Πιθανότητες μέτρησης ενέργειας:", coefficients)
print("Μέση τιμή ενέργειας:", mean_energy)
print("Αβεβαιότητα ενέργειας:", energy_uncertainty)
print(f"Κατάσταση |ψ({t})⟩:", psi_t_1)

Ιδιοτιμές: [ 1.+0.j -1.+0.j]
Ιδιοσυναρτήσεις [[-0.        -0.70710678j  0.70710678+0.j        ]
 [ 0.70710678+0.j          0.        -0.70710678j]]
Πιθανότητες μέτρησης ενέργειας: [0.5 0.5]
Μέση τιμή ενέργειας: 0.0
Αβεβαιότητα ενέργειας: 1.0
Κατάσταση |ψ(1)⟩: [0.54030231+0.j 0.84147098+0.j]
