# Numpy - πολυδιάστατοι πίνακες δεδομένων

## Εισαγωγή

Το πακέτο «numpy» (module) χρησιμοποιείται σχεδόν σε όλους τους αριθμητικούς υπολογισμούς της Python. Είναι ένα πακέτο που παρέχει διανυσματα, πίνακες και data structures πολλών διαστάσεων για την Python. Τρέχει πίσω C και Fortran, επομένως όταν οι υπολογισμοί είναι διανυσματικοί (διατυπωμένοι με διανύσματα και πίνακες), η ταχύτητα εκτέλεσης είναι πολύ καλή.

Για να χρησιμοποιήσετε το "numpy" πρέπει να εισαγάγετε το module, όπως προείπαμε:

In [4]:
from numpy import *

Στο πακέτο «numpy», η ορολογία που χρησιμοποιείται για διανύσματα, πίνακες και σύνολα δεδομένων υψηλότερων διαστάσεων είναι *array*.



## Δημιουργία «numpy» arrays

Υπάρχουν διάφοροι τρόποι για να αρχικοποιήσετε  numpy arrays, για παράδειγμα από

* μια λίστα Python ή πλειάδες (tuples)
* χρησιμοποιώντας συναρτήσεις που είναι αφιερωμένες στη δημιουργία numpy arrays, όπως «arange», «linspace» κ.λπ.
* ανάγνωση δεδομένων από αρχεία

### Από λίστες

Για παράδειγμα, για να δημιουργήσουμε νέους διανυσματικούς πίνακες και πίνακες από λίστες Python μπορούμε να χρησιμοποιήσουμε τη συνάρτηση «numpy.array».

In [18]:
# ένα διάνυσμα: το όρισμα στη συνάρτηση array είναι μια λίστα Python
E = array([1,2,3,4])

E

array([1, 2, 3, 4])

In [19]:
# ένας πίνακας: το όρισμα στη συνάρτηση array είναι μια φωλιασμένη λίστα Python
sigma_1 = array([[0, 1], [1, 0]])

sigma_1

array([[0, 1],
       [1, 0]])

Τα αντικείμενα «E» και «sigma_1» είναι και τα δύο του τύπου «ndarray» που παρέχει η ενότητα «numpy».

In [20]:
type(E), type(sigma_1)

(numpy.ndarray, numpy.ndarray)

Η διαφορά μεταξύ των arrays «E» και «sigma_1» είναι μόνο η μορφή τους. Μπορούμε να λάβουμε πληροφορίες για τη μορφή ενός πίνακα χρησιμοποιώντας την ιδιότητα «ndarray.shape».

In [21]:
E.shape

(4,)

In [22]:
sigma_1.shape

(2, 2)

Ο αριθμός των στοιχείων της array είναι διαθέσιμος μέσω της ιδιότητας «ndarray.size»:

In [23]:
sigma_1.size

4

Ισοδύναμα, θα μπορούσαμε να χρησιμοποιήσουμε τη συνάρτηση «numpy.shape» και «numpy.size»

In [24]:
shape(sigma_1)

(2, 2)

In [25]:
size(sigma_1)

4

## Άσκηση

Κατασκευάστε τον 

$$
\sigma_2 =
\begin{bmatrix}
0 & -i \\
i & 0
\end{bmatrix}
$$

και το τετραδιάνυσμα της ορμής p=(10,3,4,8)

In [26]:
sigma_y = 

print(sigma_y)

p=

print(p)

SyntaxError: invalid syntax (981767146.py, line 1)

In [7]:
sigma_y = array([[0, -1j], [1j, 0]])

print(sigma_y)

p=array([10,3,4,8])

print(p)

[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
[10  3  4  8]


Μέχρι στιγμής το «numpy.ndarray» μοιάζει πολύ με μια λίστα Python (ή ένθετη λίστα). Γιατί να μην χρησιμοποιείτε απλώς λίστες Python για υπολογισμούς αντί να δημιουργήσετε έναν νέο τύπο πίνακα;

Υπάρχουν διάφοροι λόγοι:

* Οι λίστες Python είναι πολύ γενικές. Μπορούν να περιέχουν οποιοδήποτε είδος αντικειμένου. Ορίζονται δυναμικά. Δεν υποστηρίζουν μαθηματικές συναρτήσεις όπως πολλαπλασιασμούς πινάκων και  κ.λπ. Η εφαρμογή τέτοιων συναρτήσεων για λίστες Python δεν θα ήταν πολύ αποτελεσματική λόγω του δυναμικού ορισμού τους.
* Οι Numpy πίνακες είναι **στατικά ορισμένοι** και **ομογενείς**. Ο τύπος των στοιχείων καθορίζεται όταν δημιουργείται ο πίνακας.
* Οι Numpy συστοιχίες είναι αποδοτικές στη μνήμη.
* Λόγω αυτού, η γρήγορη υλοποίηση μαθηματικών συναρτήσεων όπως ο πολλαπλασιασμός και η πρόσθεση arrays της «numpy» μπορεί να υλοποιηθεί σε μια μεταγλωττισμένη (pre-compiled) γλώσσα (χρησιμοποιείται η C και η Fortran).

Χρησιμοποιώντας την ιδιότητα «dtype» (τύπος δεδομένων) ενός «ndarray», μπορούμε να δούμε τι τύπο έχουν τα δεδομένα ενός πίνακα:

In [28]:
sigma_1.dtype

dtype('int32')

Λαμβάνουμε ένα σφάλμα εάν προσπαθήσουμε να εκχωρήσουμε μια τιμή λανθασμένου τύπου σε ένα στοιχείο σε έναν numpy πίνακα:

In [29]:
sigma_1[0,0] = "hello"

ValueError: invalid literal for int() with base 10: 'hello'

### Χρήση συναρτήσεων δημιουργίας arrays

Για μεγαλύτερες arrays δεν είναι πρακτικό να αρχικοποιήσετε τα δεδομένα με μη αυτόματο τρόπο, χρησιμοποιώντας τις λίστες της python. Αντίθετα, μπορούμε να χρησιμοποιήσουμε μία από τις πολλές συναρτήσεις στο «numpy» που δημιουργούν arrays διαφορετικών μορφών. Μερικές από τα πιο κοινές είναι:

#### arange

In [30]:
# δημιουργήστε μια σειρά

x = arange(0, 10, 1) # ορίσματα: έναρξη, διακοπή, βήμα

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x = arange(-1, 1, 0.1)

x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

#### linspace και logspace

In [8]:
# χρησιμοποιώντας το linspace, περιλαμβάνονται και τα δύο τελικά σημεία. Εδώ 25 σημεία από το 0 έως το 10.
linspace(0, 9, 25)

array([0.   , 0.375, 0.75 , 1.125, 1.5  , 1.875, 2.25 , 2.625, 3.   ,
       3.375, 3.75 , 4.125, 4.5  , 4.875, 5.25 , 5.625, 6.   , 6.375,
       6.75 , 7.125, 7.5  , 7.875, 8.25 , 8.625, 9.   ])

In [9]:
logspace(0, 9, 10, base=e)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

#### Δημιουργία ψευδοτυχαίων δεδομένων

In [34]:
from numpy import random

In [12]:
# ομοιόμορφα κατανεμημένοι τυχαίοι αριθμοί μεταξύ [0,1]
random.seed(1)
random.rand(5,5)

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02],
       [6.70467510e-01, 4.17304802e-01, 5.58689828e-01, 1.40386939e-01,
        1.98101489e-01],
       [8.00744569e-01, 9.68261576e-01, 3.13424178e-01, 6.92322616e-01,
        8.76389152e-01]])

In [36]:
# κανονικοποιημένοι τυχαίοι αριθμοί
random.randn(5,5)

array([[-0.44277614, -0.33815407, -0.19591492, -1.49787973, -0.16102545],
       [-1.93301861, -1.37527184,  0.45541737, -0.35388879,  0.62607213],
       [ 0.05933938, -0.89349176,  1.36844776, -0.1884616 , -0.33256444],
       [-0.62570894,  0.31971935,  0.3629237 ,  1.23680828, -1.76304778],
       [-1.38146984,  0.23568618,  0.24673904, -0.23572936, -0.39481136]])

#### diag

In [37]:
# Διαγώνιος πίνακας
diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [69]:
# διαγώνιος με μετατόπιση από την κύρια διαγώνιο
diag([1,2,3], k=1) 

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

#### μηδενικά και ένα

In [39]:
zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Δημιουργία και αποθήκευση αρχείου

In [78]:
#random.seed(1)
M = random.rand(3,3)

M

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01]])

In [79]:
savetxt("random-matrix.csv", M)

In [80]:
savetxt("random-matrix.csv", M, fmt='%.5f') # Το fmt καθορίζει τη μορφή

### Η εγγενής μορφή αρχείου του Numpy

Χρήσιμο κατά την αποθήκευση και την ανάγνωση δεδομένων numpy array. Χρησιμοποιήστε τις συναρτήσεις «numpy.save» και «numpy.load»:

In [81]:
save("random-matrix.npy", M)

In [82]:
load("random-matrix.npy")

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01]])

## Χειρισμός των arrays

### Ευρετηρίαση

Μπορούμε να καταχωρήσουμε στοιχεία σε έναν πίνακα χρησιμοποιώντας αγκύλες και δείκτες:

In [83]:
# Το M είναι ένας πίνακας, ή ένας πίνακας 2 διαστάσεων, που παίρνει δύο δείκτες
M[1,1]

0.14675589081711304

Εάν παραλείψουμε ένα ευρετήριο ενός πολυδιάστατου πίνακα, επιστρέφει ολόκληρη τη σειρά (ή, γενικά, έναν πίνακα διαστάσεων N-1)

In [84]:
M

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01]])

In [85]:
M[1]

array([0.30233257, 0.14675589, 0.09233859])

Το ίδιο πράγμα μπορεί να επιτευχθεί χρησιμοποιώντας το «:» αντί για ένα ευρετήριο:

In [49]:
M[1,:] # σειρά 1

array([0.04829479, 0.0785032 , 0.44056288])

In [50]:
M[:,1] # στήλη 1

array([0.28116945, 0.0785032 , 0.420895  ])

Μπορούμε να εκχωρήσουμε νέες τιμές σε στοιχεία ενός πίνακα χρησιμοποιώντας την ευρετηρίαση:

In [51]:
M[0,0] = 1

In [52]:
M

array([[1.        , 0.28116945, 0.7272711 ],
       [0.04829479, 0.0785032 , 0.44056288],
       [0.08347799, 0.420895  , 0.15667932]])

In [86]:
# λειτουργεί επίσης για γραμμές και στήλες
M[1,:] = 0
M[:,2] = -1

In [87]:
M

array([[ 0.417022  ,  0.72032449, -1.        ],
       [ 0.        ,  0.        , -1.        ],
       [ 0.18626021,  0.34556073, -1.        ]])

### Τεμαχισμός ευρετηρίου

Η κοπή ευρετηρίου (Index Slicing) είναι το τεχνικό όνομα για τη σύνταξη «M[lower:upper:step]» για την εξαγωγή μέρους ενός πίνακα:

In [55]:
A = array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [56]:
A[1:3]

array([2, 3])

Οι φέτες  πίνακα είναι *μεταβλητές*: εάν τους εκχωρηθεί μια νέα τιμή, ο αρχικός πίνακας από τον οποίο εξάχθηκε το slice τροποποιείται:

In [57]:
A[1:3] = [-2,-3]

A

array([ 1, -2, -3,  4,  5])

Μπορούμε να παραλείψουμε οποιαδήποτε από τις τρεις παραμέτρους στο `M[lower:upper:step]`:

In [58]:
A[::] # κάτω, πάνω, βήμα όλα παίρνουν τις προεπιλεγμένες τιμές

array([ 1, -2, -3,  4,  5])

In [59]:
A[::2] # Το βήμα είναι 2, και αρχή και  τέλος του πίνακα

array([ 1, -3,  5])

In [60]:
A[:3] # τρία πρώτα στοιχεία

array([ 1, -2, -3])

In [61]:
A[3:] # στοιχεία ξεκινώντας από τον δείκτη 3

array([4, 5])

Οι αρνητικοί δείκτες μετράνε από το τέλος του πίνακα (θετικός δείκτης από την αρχή):

In [62]:
A = array([1,2,3,4,5])

In [63]:
A[-1] # το τελευταίο στοιχείο του πίνακα

5

In [64]:
A[-3:] # τα τρία τελευταία στοιχεία

array([3, 4, 5])

### Βασικές λειτουργίες Numpy

#### Δημιουργία Arrays

Γράψτε κώδικα που να δημιουργεί μια numpy array με τις τιμές και έναν άλλο με τα τετράγωνα αυτών των αριθμών.

#### Γεννήτριες Πινάκων

Χρησιμοποιήστε τις συναρτήσεις arange και linspace για να δημιουργήσετε πίνακες αριθμών μεταξύ 0 και 10.

#### Πράξεις σε Arrays

Δοσμένοι δύο πίνακες  και , υπολογίστε το άθροισμα, τη διαφορά

In [ ]:
import numpy as np

In [ ]:
# 1. Δημιουργία Arrays
arr = np.array([1, 2, 3, 4, 5])
arr_squared = ...
print("Πίνακας:", arr)
print("Τετράγωνα:", arr_squared)

In [ ]:
# 2. Γεννήτριες Πινάκων
arr_arange = np.arange(...,...,...)  # Από 0 έως 10 με βήμα 1
arr_linspace = np.linspace(...,...,...)  # 11 σημεία μεταξύ 0 και 10
print("arange:", arr_arange)
print("linspace:", arr_linspace)

In [ ]:
# 3. Πράξεις σε Arrays
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

sum_AB = ...
diff_AB = ...

print("Άθροισμα:", sum_AB)
print("Διαφορά:", diff_AB)

In [ ]:
import numpy as np

# 1. Δημιουργία Arrays
arr = np.array([1, 2, 3, 4, 5])
arr_squared = arr ** 2
print("Πίνακας:", arr)
print("Τετράγωνα:", arr_squared)

# 2. Γεννήτριες Πινάκων
arr_arange = np.arange(0, 11, 1)  # Από 0 έως 10 με βήμα 1
arr_linspace = np.linspace(0, 10, 11)  # 11 σημεία μεταξύ 0 και 10
print("arange:", arr_arange)
print("linspace:", arr_linspace)

# 3. Πράξεις σε Arrays
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

sum_AB = A + B
diff_AB = A - B
dot_product = np.dot(A, B)

print("Άθροισμα:", sum_AB)
print("Διαφορά:", diff_AB)
print("Εσωτερικό γινόμενο:", dot_product)
